In [1]:
import torch

## 对称矩阵$A$等于其转置：$A = A^T$

In [2]:
B = torch.tensor([[1, 2, 3],
                  [2, 0, 4],
                  [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [3]:
# 拓展：关于reshape
A = torch.arange(20, dtype=torch.float32)
A_reshape = A.reshape((4, 5))
A_reshape[:] = 1.
A_reshape, A  # A_reshape只是A的一个view，修改A_reshape的值，A也会变化

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]))

## A.clone() 的应用

In [4]:
A = torch.tensor([1.0])
B = A
print(id(A) == id(B))  # 不会给B分配新的内存

C = A.clone()
print(id(A) == id(C))  # 给C分配新的内存

True
False


## 张量的元素和

In [5]:
A = torch.arange(20*2, dtype=torch.float32).reshape((2, 5, 4))
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [6]:
# axis = 0
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0_keep = A.sum(axis=0, keepdims=True)  # 求和后不把第0个维度丢掉，对后续做广播机制有好处！
A_sum_axis0, A_sum_axis0.shape, A_sum_axis0_keep.shape  # 相当于把两个5x4的tensor按元素相加，第0个维度消失

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]),
 torch.Size([1, 5, 4]))

In [7]:
# axis = 1
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape  # 相当于对每一个5x4的tensor操作，每一列所有元素相加，第1个维度消失

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [8]:
# axis = 2
A_sum_axis2 = A.sum(axis=2)
A_sum_axis2, A_sum_axis2.shape  # 相当于对每一个5x4的tensor操作，每一行所有元素相加，第2个维度消失

(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [9]:
# axis = [0, 1]
print(A.sum(axis=[0, 1]).shape)  # 第0个维度和第1个维度均消失
A.sum(axis=0).sum(axis=0) == A.sum(axis=[0, 1])

torch.Size([4])


tensor([True, True, True, True])

## 求均值、累加、点积、矩阵x向量、矩阵x矩阵、范数

In [10]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [11]:
# 按特定的维度求均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [12]:
# 累加
A.cumsum(axis=1)

# 点积：torch.dot(a, b)
# 矩阵x向量：torch.mv(A, b)
# 矩阵x矩阵：torch.mm(A, B)
# 范数L2：torch.norm(v)，对于矩阵求的是Frobenius norm范数（F范数）
# 范数L1：torch.abs(v).sum()

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])